project_name: iris_classifier
random_state : 42
test_size: 0.2

data:
  source: sklearn_iris
  path: ""
   
preprocessing:
  scaler: standard


model:
   type: logestic_regression
   params:
     max_iter: 1000
     solver: lbfgs

output:
   model dir : artifacts/model
   model_filename: model.joblib
   metadata_filename: meta.json